Import('env')

# This will build the intermediate objects required for the library
SConscript(["SConscript.cctbx", "SConscript.newmat", "SConscript.objcryst"])

# This retrieves the intermediate objects
newmatobjs = env["newmatobjs"]
cctbxobjs = env["cctbxobjs"]
objcrystobjs = env["objcrystobjs"]

# This builds the shared library
sl = env.SharedLibrary("objcryst", objcrystobjs + cctbxobjs + newmatobjs)
env.Alias("installlib", env.Install("../boost", sl))


# FIXME - need a portable way to install library!!!
# Pick where to install the shared library
import os
if os.name == 'posix':
    libdir = os.environ.get("LIBDIR")
    if libdir is None or not os.path.exists(libdir):
        libdir = "/usr/lib"
    env.Alias("installlib", env.Install(libdir, sl))

# Put this in the environment
env["objcrystlib"] = sl
